spring:
  application:
    name: orders
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        order-out:
          destination: orders
          content-type: application/json
      rabbit:
        bindings:
          order-out:
            producer:
              routing-key-expression: headers['routingKey']
spring:
  output:
    ansi:
      enabled: ALWAYS
  logging:
    pattern:
      console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"